services:
  ms-config-server:
    image: ms-config-server:1.0.1
    restart: always
    mem_limit: 400m
    ports:
      - "8888:8888"
    volumes:
      - C:\Users\Mirko Alarcon\Documents\UCB\I-2023\ArqSoftware\ProyectoMS\serv_conf\logs:/Users/Mirko Alarcon/Documents/UCB/I-2023/ArqSoftware/ProyectoMS/serv_conf/logs
    networks:
        - mrk27-network

  zipkin:
    image: openzipkin/zipkin
#    container_name: zipkin-server
    ports:
      - "9411:9411"
    networks:
        - mrk27-network

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
        - mrk27-network

networks:
    mrk27-network:
      external: true

