server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:nini1304/Proy_server-config.git
          ignoreLocalSshSettings: true
          hostkey: AAAAB3NzaC1yc2EAAAADAQABAAABgQCkmwi2V46kwpUiKwnJ5kmvSvy8A1dvOCrMhaNfBUnOdUE0HHQPNoQ0FBBNrHEtn17czY9dN+YGkcyexI+QbX6fOMaiFvCot0Yc5XmzuOP+4YEA+5OWu3aALYSAp94eCy5z7himDNXgcLlkIYzyF1ajGIa+Juae4pxLrE7bkJzOrA4ZMZSYmQUmUmwH2mO4MlTwbvlqkrIZIdfadxkdq8PE5iHZPVdJahi2OUoITtX96i6WK3mPH+LGXTWfSSFpwodWPXh8La9KdP/brBuLV8YHMO+BYKF6OmU3rQ0ywRArV2IHTssYrSFdDA5UvgsPeQCiJKd3YbMAh7ft03Vb5EdUfvT7dewpobRJ8zSzXKRLcbNUxx7ndxKQWCc6hCmGAgXigGi1mjY643h1wcEf5EA5vIsGRuqjYq5w6AsDdMhUfaApOCQD3+ukogpgGVd2OtIF4x+MoH5YCcMetOg0AhA+gRzsWYd625ILx+m1GzQBgFd0EbozgliybsOK0RBsnyU= geraldine.ibieta@ucb.edu.bo
          host-key-algorithm: ssh-rsa
          private-key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAYEApJsItleOpMKVIisJyeZJr0r8vANXbzgqzIWjXwVJznVBNBx0DzaE
            NBQQTaxxLZ9e3M2PXTfmBpHMnsSPkG1+nzjGohbwqLdGHOV5s7jj/uGBAPuTlrt2gC2EgK
            feHgsuc+4YpgzV4HC5ZCGM8hdWoxiGvibmnuKcS6xO25CczqwOGTGUmJkFJlJsB9pjuDJU
            8G75apKyGSHX2ncZHavDxOYh2T1XSWoYtjlKCE7V/eoulit5jx/ixl01n0khacKHVj14fC
            2vSnT/26wbi1fGBzDvgWChejplN60NMsEQK1diB07LGK0hXQwOVL4LD3kAoiSnd2GzAIe3
            7dN1W+RHVH70+3XsKaG0SfM0s1ykS3GzVMce53cSkFgnOoQphgIF4oBotZo2OuN4dcHBH+
            RAObyLBkbqo2KucOgLA3TIVH2gKTgkA9/rpKIKYBlXdjrSBeMfjKB+WAnDHrToNAIQPoEc
            7FmHetuSC8fptRs0AYBXdBG6M4JYsm7DitEQbJ8lAAAFkCDtwKsg7cCrAAAAB3NzaC1yc2
            EAAAGBAKSbCLZXjqTClSIrCcnmSa9K/LwDV284KsyFo18FSc51QTQcdA82hDQUEE2scS2f
            XtzNj1035gaRzJ7Ej5Btfp84xqIW8Ki3RhzlebO44/7hgQD7k5a7doAthICn3h4LLnPuGK
            YM1eBwuWQhjPIXVqMYhr4m5p7inEusTtuQnM6sDhkxlJiZBSZSbAfaY7gyVPBu+WqSshkh
            19p3GR2rw8TmIdk9V0lqGLY5SghO1f3qLpYreY8f4sZdNZ9JIWnCh1Y9eHwtr0p0/9usG4
            tXxgcw74FgoXo6ZTetDTLBECtXYgdOyxitIV0MDlS+Cw95AKIkp3dhswCHt+3TdVvkR1R+
            9Pt17CmhtEnzNLNcpEtxs1THHud3EpBYJzqEKYYCBeKAaLWaNjrjeHXBwR/kQDm8iwZG6q
            NirnDoCwN0yFR9oCk4JAPf66SiCmAZV3Y60gXjH4ygflgJwx606DQCED6BHOxZh3rbkgvH
            6bUbNAGAV3QRujOCWLJuw4rREGyfJQAAAAMBAAEAAAGAYzo+R0WC7NmL81wEe5yCYNSQhH
            pzM82lJ0OMV5SliHrwwoxAfoc7rPVHWruQQpNnKS4VtXkkBmPP+Qm/Da6j/THJtB6mFt7c
            ukCvW+MiNh0UmlYOA3igl+ZYkQIhCPVunF40p6znJXRunekHwUzGYm0/lNN4hOFQnOGTbB
            LCJGhd21wjGtZr300iaJ2DLZ/Rylrrqg4ipLndGIphLpzD2Cdu0jmDK/N0UC067sUvhPCu
            AsLUda4gE7pOv+Xi6ZFk8lNdNltZpynzUK4LHz6E4UrQ9WwX2Ar4W8rPfLfwqXMGJGHZ48
            +Sj7zuQJa6TALog3iwNlIKTn0zq0RRndI5oIA89phXVCGZx+UMwMccJNyB/LtNaEHkQbuT
            z3kajhGTgfvrqgR7nRpqRRPLpfcxm7arRY46ZqW2VYH7P6g7fQgdZNIi/kGAT+7qDqChPa
            nLtM7Gq9U3xerdddblzMy3oab4BYuZbUesXkR0RJ6vMMTlKblIooFXEZuhTbA+EwtlAAAA
            wHZKCBXHSvtbHKoKf2xoAN/FGz71WICHk/zX1Ksk0d+dMt4x6VshIBd7INsVbMkEZWUbGu
            JGSkbYDMq0ItAQcRkUUrbrKyZZt9O2vtDe1jkVC/GW4fygnt4RhU1qKSwwI8BwCpnmEOpj
            /dZrptnLSKDoEkXxmUoc4MqlofNdFnawgiCQnNZoRm0cBgUgZIa1uKCx6vALivRK8VO+F4
            yW9y4YgribKBkWVM1RVWNGSJfBDu2NV57l4LNOgXVTBZoe5wAAAMEA21QnU63v34vCQo9D
            MvMh2yp1gCURKcYulG9ICWX99o4BDEW/wV5udcNIRuKysR2UGIk4bm5lmAioVAUmU3eb+y
            rqFF6NOy2J2UOUWSSufNx5xgxiKXlo0wsbbbHpmdc+1VXbY3vHXkf2xnIA76nawDLc18WR
            JhGXtuJvbhvVSquh1EwyJKCV8lg/jDst8ALRsaK3eKKDCAT4lmeoyc+qf5IamdzD4MDgGi
            wEL48OgdbsSoJB+f3D6WrGljiBE+dPAAAAwQDAIJY3RqP/e+cbdZTmp4aREwN0Q0yItPUn
            WF5CA+1siPIZ3C60L9HjXgPD1mOKo6HWo3ONJqUO0XU3CjWXkNL2TcsBfqkNM4D4FXqqqR
            e3XijxDZMwi+SKSTt/f2Q4u3nE2SDaz4e29zoFUyeJjC53wQm4o8iqVOYonJi9tsHmW8qh
            GhvLUzlotTp/gizGeQzdHbx2H7fqJQapN5Z+QvusrrR7lcobyP/OZF39BFsNRAWqClAEu6
            tV4h/6IE7jtUsAAAAbZ2VyYWxkaW5lLmliaWV0YUB1Y2IuZWR1LmJv
            -----END OPENSSH PRIVATE KEY-----
          skip-ssl-validation: true
          strict-host-key-checking: false
  application:
    name: ms-config-server

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8701/eureka/

